services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - my_modules:/app/node_modules
    ports:
      - "1234:1234"
    command: tail -f /dev/null
volumes:
  my_modules: